version: '3.8'

services:
  api:
    container_name: unbench_backend_api
    image:  mtharwat/unbench-backend
    # command: python manage.py runserver 0.0.0.0:8000
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/api
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: contact_test
      POSTGRES_USER: root  
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"



  
