# Generated by Django 3.2.23 on 2024-01-14 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='version',
        ),
    ]
