# Generated by Django 3.2.23 on 2024-01-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20240112_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='version',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
